version: '3.5'

services:
  app: 
      image: node:12-alpine
      volumes:
        - ./:/app:cached
      working_dir: /app
      ports:
        - 30:3000
      command: npm start
      tty: true
      